### ISSUE TITLE
Can't parse QR when large claim

### ISSUE THREAD

**Issue by sinsinpurin** [microsoft/ClaimQR#1]
When I test to create QR VC what includes did:ion(many characters), it can create QR but can't verify QR.

testing vc (masaki-issuer/jwt.json)
```
{
  "iss": "did:ion:EiA86kbo6KlmoYaUSchoIBSYqwK37AHpoD_qMT4Uk-zABw:eyJkZWx0YSI6eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljS2V5cyI6W3siaWQiOiJzaWduaW5nIiwicHVibGljS2V5SndrIjp7ImNydiI6InNlY3AyNTZrMSIsImt0eSI6IkVDIiwieCI6IldCSWFYTlJnYjFfbEVHdVdOTFJPbUdtNkZISWJfMHB6TFhMdEZrYVRuLVEiLCJ5IjoiNGNKYXRDTXFVM0RBNGJoVldOdGtqc1RFX3hmd0FhNnk2NF9RWjdVZ1ktOCJ9LCJwdXJwb3NlcyI6WyJhdXRoZW50aWNhdGlvbiIsImtleUFncmVlbWVudCJdLCJ0eXBlIjoiRWNkc2FTZWNwMjU2azFWZXJpZmljYXRpb25LZXkyMDE5In1dLCJzZXJ2aWNlcyI6W119fV0sInVwZGF0ZUNvbW1pdG1lbnQiOiJFaUJra1dIOXJTMmxrVDJnT2Y0dEdWY3A3V2R3UUhJVFdqaXotVUpnOUFvU1NnIn0sInN1ZmZpeERhdGEiOnsiZGVsdGFIYXNoIjoiRWlDaVl0cTE5YmVwVFZHZE1hRUh4Q2MtU0hBTTl1NlRSeEg5b21vUDJod09LdyIsInJlY292ZXJ5Q29tbWl0bWVudCI6IkVpREp4ZmlCdFdRc09nZ0F6ZWpBZUdfUkZCWHFObXZ6QXhnb3l5QkhiWVYwaVEifX0",
  "sub": "did:ion:EiA86kbo6KlmoYaUSchoIBSYqwK37AHpoD_qMT4Uk-zABw:eyJkZWx0YSI6eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljS2V5cyI6W3siaWQiOiJzaWduaW5nIiwicHVibGljS2V5SndrIjp7ImNydiI6InNlY3AyNTZrMSIsImt0eSI6IkVDIiwieCI6IldCSWFYTlJnYjFfbEVHdVdOTFJPbUdtNkZISWJfMHB6TFhMdEZrYVRuLVEiLCJ5IjoiNGNKYXRDTXFVM0RBNGJoVldOdGtqc1RFX3hmd0FhNnk2NF9RWjdVZ1ktOCJ9LCJwdXJwb3NlcyI6WyJhdXRoZW50aWNhdGlvbiIsImtleUFncmVlbWVudCJdLCJ0eXBlIjoiRWNkc2FTZWNwMjU2azFWZXJpZmljYXRpb25LZXkyMDE5In1dLCJzZXJ2aWNlcyI6W119fV0sInVwZGF0ZUNvbW1pdG1lbnQiOiJFaUJra1dIOXJTMmxrVDJnT2Y0dEdWY3A3V2R3UUhJVFdqaXotVUpnOUFvU1NnIn0sInN1ZmZpeERhdGEiOnsiZGVsdGFIYXNoIjoiRWlDaVl0cTE5YmVwVFZHZE1hRUh4Q2MtU0hBTTl1NlRSeEg5b21vUDJod09LdyIsInJlY292ZXJ5Q29tbWl0bWVudCI6IkVpREp4ZmlCdFdRc09nZ0F6ZWpBZUdfUkZCWHFObXZ6QXhnb3l5QkhiWVYwaVEifX0",
  "vc": {
    "@context": ["https://www.w3.org/2018/credentials/v1"],
    "type": ["VerifiableCredential", "Credential"],
    "credentialSubject": {
      "name": "name",
      "age": "18"
    }
  },
  "nbf": 1638507401,
  "exp": 2038511001,
  "jti": "d0577601-a431-4959-aba2-4a14d33b7b8b"
}
```

Error Message
```
> claimqr@0.1.0 verify-qr
> ts-node --files src/verify-qr-cl.ts "--qrPath" "./masaki-issuer/qr.png" "--jwtPath" "./masaki-issuer/outjwt.json" "--jwksPath" "./masaki-issuer/.well-known/jwks.json"

Verifying QR image from ./masaki-issuer/qr.png
Error: Can't parse QR code
    at decodeQr (/Users/masakiobayashi/main/Blockbase/ClaimQR/src/verify-qr.ts:70:19)
    at verifyQrFiles (/Users/masakiobayashi/main/Blockbase/ClaimQR/src/verify-qr.ts:171:18)
    at async /Users/masakiobayashi/main/Blockbase/ClaimQR/src/verify-qr-cl.ts:26:9
```

I think it not working decoding QR (jsqr module)...

**Comment by christianpaquin** [comment]
Indeed, it looks like jsQR can't parse the error; it's internal scanning function returns null; not sure what the issue is. This being said, the input JWT payload is not compliant with this project's specification. The `iss` claim must be a URL from which the issuer public key set can be retrieved. A DID-based VC is likely too big to fit in the expected QR size (max [version 22](https://www.qrcode.com/en/about/version.html)).
